version: "1.0"
stages:
  - "clone"
  - "build"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "prabusubra/React-JSONUI"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "prabusubra/React-JSONUI"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  
